version: "3.8"
services:
  web:
    image: lqwangxg/node
    command: sh -c "npm install &&  npm run start"
    working_dir: /app
    volumes:
      - ~/todo/:/app
      - ~/todo/db:/etc/todos
    ports:
      - 3000:3000
